### ISSUE TITLE
NFS share size 

### ISSUE THREAD

**Issue by emahn** [gdha/sgesap_validation#31]
Just looking at your script I saw that you point a limit of 4096 characters for nfs share. 
I know that on sg 11.18 the limit is 1023 (indeed I was testing the limit).
Message is : "Value specified for nfs/hanfs_export/XFS is too long. Its length should not exceed 1023 characters."
Can you check on the 11.20 ? 
As far as I know  the limit of 4096 is for the "share" command (as in the dfstab). 
Comment : 
Sorry I just realized that it was on on an HP-UX server, perhaps your script is just  focused on Linux.

**Comment by gdha** [comment]
@emahn The sgesap_validation script works only for SG 11.20 (or higher) where we had once a case with HP concerning the exceeding length and it was confirmed that 4096 characters is the limit for NFS share on HP-UX 11.31 with SG 11.20
